### ISSUE TITLE
[Tracker] Minecraft 1.21

### ISSUE THREAD

**Issue by AlisaAkiron** [NibiruResearchCenter/nibiru-smp#1]
Server core:

- [ ] [PaperMC (stable)](https://papermc.io/downloads/all)

Important Plugins:

- [ ] [CoreProtect](https://modrinth.com/plugin/coreprotect/versions)
- [x] [CustomCrafting](https://modrinth.com/plugin/customcrafting/versions)
- [x] [LuckPerms](https://luckperms.net/download)
- [x] [spark](https://spark.lucko.me/download)

Unimportant Plugins:

- [ ] [Maintenance](https://modrinth.com/plugin/maintenance/versions)
- [ ] [Plan Player Analytics](https://hangar.papermc.io/AuroraLS3/Plan-Player-Analytics)
- [x] [WorldEdit](https://modrinth.com/plugin/worldedit/versions)
